FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

RUN pnpm install

COPY . .

EXPOSE 50053

CMD sh -c "sleep 5 && cd services/notification-service && pnpm exec prisma migrate dev && pnpm --filter notification-service start:dev"